# Generated by Django 4.0.2 on 2022-03-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='data',
            new_name='dated',
        ),
    ]
