# Generated by Django 4.0.2 on 2022-03-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_options_rename_data_expense_dated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='dated',
            new_name='date',
        ),
    ]
