# Generated by Django 4.0.2 on 2022-03-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprefrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprefrences',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=255, null=True),
        ),
    ]
